<MyLayout>
      
    GridLayout:
        cols:1
        size: root.width-200, root.height-200
        pos: 100, 100
        Label:
            text: 'maxDemon - machine learning for functional variant analyses'
            font_size: 24
            size_hint: 0.5, 0.2
            bold: True
            color: 0.1, 0.85, 0.85, 1
        Label:
            text: 'GPL3 license - GA Babbitt Lab at Rochester Institute of Technology'
            font_size: 16
            size_hint: 0.3, 0.1    
        GridLayout:
            cols:1
            Image:
                source: 'maxdemon.png'
                size_hint: 0.6, 0.6
            Label:
                text: "machine learning stack"
                bold: True
                size_hint: 0.3, 0.1
                color: 1, 0, 0, 1
                font_size: 20
            Label:
                text: ''
                font_size: 16
                size_hint: 0.3, 0.1             
            GridLayout:
                canvas:
                    Color:
                        rgba: 0.8, 0.8, 0.85, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                cols:2
                Label:
                    text: "KNN - K nearest neighbors"
                    size_hint: 0.3, 0.1
                    color: 0, 0, 0, 1
                    bold: True
                CheckBox:
                    id: ml1
                    on_active: root.ml1()
                    color: 0, 0, 0, 1
                    active: True
                Label:
                    text: "naiveBayes/LDA/QDA - probablistic learning"
                    size_hint: 0.3, 0.1
                    color: 0, 0, 0, 1
                    bold: True
                CheckBox:
                    id: ml2
                    on_active: root.ml2()
                    color: 0, 0, 0, 1
                    active: True
                Label:
                    text: "SVM - support vector machine"
                    size_hint: 0.3, 0.1
                    color: 0, 0, 0, 1
                    bold: True
                CheckBox:
                    id: ml3
                    on_active: root.ml3()
                    color: 0, 0, 0, 1
                    active: True
                Label:
                    text: "randomForest/adaboost - ensemble learning"
                    size_hint: 0.3, 0.1
                    color: 0, 0, 0, 1
                    bold: True
                CheckBox:
                    id: ml4
                    on_active: root.ml4()
                    color: 0, 0, 0, 1
                    active: True
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1     
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1
                Button:
                    id: btn1
                    text: "(1) run new MD sims for deployment"
                    on_press: root.btn1()
                    background_color: 0.1, 0.9, 0.9, 1
                Button:
                    id: btn2
                    text: "(2) process DROIDS training set"   
                    on_press: root.btn2()
                    background_color: 0.1, 0.9, 0.9, 1
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1    
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1
                Button:
                    id: btn3
                    text: "(3) deploy machine learning"   
                    on_press: root.btn3()
                    background_color: 0.1, 0.9, 0.9, 1
                Button:
                    id: btn4
                    text: "(4) plot conserved dynamics and impacts"   
                    on_press: root.btn4()
                    background_color: 0.1, 0.9, 0.9, 1
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1    
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1
                Button:
                    id: btn5
                    text: "(5) show image of conserved dynamics"
                    on_press: root.btn5()
                    background_color: 0.1, 0.9, 0.9, 1
                Button:
                    id: btn6
                    text: "(6) render movies of learning process"   
                    on_press: root.btn6()
                    background_color: 0.1, 0.9, 0.9, 1
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1    
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1
                Button:
                    id: btn7
                    text: "(7) show image(s) of variant impacts"   
                    on_press: root.btn7()
                    background_color: 0.1, 0.9, 0.9, 1
                Button:
                    id: btn8
                    text: "(8) play movies of learners"   
                    on_press: root.btn8()
                    background_color: 0.1, 0.9, 0.9, 1
                
                